name: Sandcat Basic

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Mod tidy
      run: |
        cd gocat
        go mod tidy

    - name: Build Windows
      run: |
        cd gocat
        go build -o sandcat.go-windows -ldflags="-s -w" sandcat.go
        file sandcat.go-windows && ls -al sandcat.go-windows
      env:
        GOOS: windows

    - name: Build Darwin
      run: |
        cd gocat
        go build -o sandcat.go-darwin -ldflags="-s -w" sandcat.go
        file sandcat.go-darwin && ls -al sandcat.go-darwin
      env:
        GOOS: darwin

    - name: Build Linux
      run: |
        cd gocat
        go build -o sandcat.go-linux -ldflags="-s -w" sandcat.go
        file sandcat.go-linux && ls -al sandcat.go-linux && ./sandcat.go-linux -help
      env:
        GOOS: linux

    - name: Golang Unit Tests
      run: |
        cd gocat
        go test -v ./...
